if(APPLE)
  enable_language(OBJC OBJCXX)
endif()

# Mac Catalyst builds through `haylen-catalyst.toolchain.cmake` compile for the `macabi` flavor of iOS, so the engine treats them as iOS.
if(CMAKE_CXX_COMPILER_TARGET MATCHES "-macabi$")
  set(HAYLEN_CATALYST ON)
else()
  set(HAYLEN_CATALYST OFF)
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "iOS" OR HAYLEN_CATALYST)
  set(HAYLEN_PLATFORM "ios")
elseif(CMAKE_SYSTEM_NAME STREQUAL "tvOS")
  set(HAYLEN_PLATFORM "tvos")
elseif(ANDROID)
  set(HAYLEN_PLATFORM "android")
elseif(EMSCRIPTEN)
  set(HAYLEN_PLATFORM "web")
elseif(WIN32)
  set(HAYLEN_PLATFORM "windows")
elseif(APPLE)
  set(HAYLEN_PLATFORM "macos")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(HAYLEN_PLATFORM "linux")
else()
  message(FATAL_ERROR "The platform \"${CMAKE_SYSTEM_NAME}\" is not supported.")
endif()

if(HAYLEN_PLATFORM MATCHES "^(macos|windows|linux)$")
  set(HAYLEN_DESKTOP ON)
else()
  set(HAYLEN_DESKTOP OFF)
endif()

# The function `haylen_add_app` runs in the folders of the apps, which do not see the variables of the engine folder.
set(HAYLEN_PLATFORM "${HAYLEN_PLATFORM}" CACHE INTERNAL "Platform the engine is built for.")
set(HAYLEN_DESKTOP "${HAYLEN_DESKTOP}" CACHE INTERNAL "Whether the platform is a desktop.")

# Lua is compiled as C++ by Varn, so a Lua error unwinds as a C++ exception and the browser build needs exception support.
if(EMSCRIPTEN)
  add_compile_options(-fexceptions)
  add_link_options(-fexceptions)
endif()

set(HAYLEN_BACKEND "${HAYLEN_RENDER_BACKEND}")
if(HAYLEN_BACKEND STREQUAL "AUTO")
  if(APPLE)
    set(HAYLEN_BACKEND "METAL")
  elseif(WIN32)
    set(HAYLEN_BACKEND "D3D11")
  elseif(ANDROID)
    set(HAYLEN_BACKEND "GLES3")
  elseif(EMSCRIPTEN)
    set(HAYLEN_BACKEND "WGPU")
  else()
    set(HAYLEN_BACKEND "GLCORE")
  endif()
endif()

if(NOT HAYLEN_BACKEND MATCHES "^(METAL|D3D11|GLCORE|GLES3|WGPU)$")
  message(FATAL_ERROR "The rendering backend \"${HAYLEN_BACKEND}\" is not supported.")
endif()

message(STATUS "Haylen platform: \"${HAYLEN_PLATFORM}\"")
message(STATUS "Haylen rendering backend: \"${HAYLEN_BACKEND}\"")
