if(NOT HAYLEN_SANITIZERS MATCHES "^(OFF|ADDRESS|THREAD)$")
  message(FATAL_ERROR "The option \"HAYLEN_SANITIZERS\" is \"OFF\", \"ADDRESS\" or \"THREAD\", not \"${HAYLEN_SANITIZERS}\".")
endif()

# ThreadSanitizer sees only the synchronization of the code it instruments, such as the atomics with which libuv wakes its loop, so it instruments the dependencies too.
if(HAYLEN_SANITIZERS STREQUAL "THREAD" AND HAYLEN_DESKTOP AND NOT MSVC)
  add_compile_options(-fsanitize=thread -fno-omit-frame-pointer)
  add_link_options(-fsanitize=thread)
endif()

# The fuzzer learns from the coverage of everything it reaches, so a fuzzing build instruments every target, the dependencies included, and checks their memory with AddressSanitizer. Only a Clang that links libFuzzer builds it.
if(HAYLEN_BUILD_FUZZERS)
  include(CheckCXXSourceCompiles)
  set(CMAKE_REQUIRED_LINK_OPTIONS -fsanitize=fuzzer)
  check_cxx_source_compiles("#include <cstddef>\n#include <cstdint>\nextern \"C\" int LLVMFuzzerTestOneInput(const std::uint8_t*, std::size_t) { return 0; }" HAYLEN_FUZZER_LINKS)
  unset(CMAKE_REQUIRED_LINK_OPTIONS)
  if(NOT HAYLEN_FUZZER_LINKS)
    message(FATAL_ERROR "The option \"HAYLEN_BUILD_FUZZERS\" needs a Clang that links libFuzzer, and \"${CMAKE_CXX_COMPILER}\" does not.")
  endif()
  add_compile_options(-fsanitize=fuzzer-no-link,address -fno-omit-frame-pointer)
  add_link_options(-fsanitize=address)
endif()

function(haylen_enable_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /permissive- /Zc:preprocessor /utf-8)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -Wshadow)
    # Designated initializers that leave fields to their default member values are the intended style.
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      target_compile_options(${target} PRIVATE -Wno-missing-designated-field-initializers)
    else()
      target_compile_options(${target} PRIVATE -Wno-missing-field-initializers)
    endif()
  endif()

  if(HAYLEN_SANITIZERS STREQUAL "ADDRESS" AND HAYLEN_DESKTOP AND NOT MSVC)
    target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=address,undefined)
  endif()
endfunction()
