# Builds the engine as an SDK that other projects find with `find_package(haylen)`.
# Every static library the engine needs is merged into one `haylen` library, and the runtime into `haylen_runtime`, so the package config imports two libraries for the platform the SDK was built for.
# The SDK installs with `cmake --install <build> --component haylen_sdk`, which leaves out the install rules of the dependencies.

include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

# Collects the static libraries a target links, directly or through other targets, and the system libraries and flags they need.
function(haylen_static_closure target out_archives out_externals)
  set(archives)
  set(externals)
  set(visited)
  set(pending ${target})
  while(pending)
    list(POP_FRONT pending item)
    if(item IN_LIST visited)
      continue()
    endif()
    list(APPEND visited "${item}")
    if(NOT TARGET "${item}")
      list(APPEND externals "${item}")
      continue()
    endif()

    get_target_property(aliased "${item}" ALIASED_TARGET)
    if(aliased)
      list(APPEND pending "${aliased}")
      continue()
    endif()
    get_target_property(type "${item}" TYPE)
    get_target_property(imported "${item}" IMPORTED)
    if(type STREQUAL "STATIC_LIBRARY")
      list(APPEND archives "${item}")
    endif()

    # Targets built here keep their private dependencies in `LINK_LIBRARIES`, and every target keeps its public ones in `INTERFACE_LINK_LIBRARIES`.
    set(properties INTERFACE_LINK_LIBRARIES)
    if(NOT imported AND NOT type STREQUAL "INTERFACE_LIBRARY")
      list(APPEND properties LINK_LIBRARIES)
    endif()
    foreach(property IN LISTS properties)
      get_target_property(links "${item}" ${property})
      if(NOT links)
        continue()
      endif()
      foreach(link IN LISTS links)
        # Wrappers nest, as in `$<LINK_ONLY:$<BUILD_LOCAL_INTERFACE:ZLIB::ZLIB>>`, so they come off one layer at a time.
        set(unwrapped "")
        while(NOT unwrapped STREQUAL link)
          set(unwrapped "${link}")
          string(REGEX REPLACE "^\\$<(LINK_ONLY|BUILD_INTERFACE|BUILD_LOCAL_INTERFACE):(.*)>$" "\\2" link "${link}")
        endwhile()
        if(link STREQUAL "" OR link MATCHES "^::@" OR link MATCHES "^\\$<INSTALL_INTERFACE:")
          continue()
        endif()
        if(link MATCHES "\\$<")
          message(FATAL_ERROR "The SDK cannot follow the link item \"${link}\" of \"${item}\".")
        endif()
        list(APPEND pending "${link}")
      endforeach()
    endforeach()
  endwhile()

  list(REMOVE_DUPLICATES externals)
  set(${out_archives} ${archives} PARENT_SCOPE)
  set(${out_externals} ${externals} PARENT_SCOPE)
endfunction()

set(sdk "${CMAKE_BINARY_DIR}/haylen-sdk")
set(sdk_libraries "${sdk}/$<CONFIG>")
set(engine_library "${sdk_libraries}/${CMAKE_STATIC_LIBRARY_PREFIX}haylen${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(runtime_library "${sdk_libraries}/${CMAKE_STATIC_LIBRARY_PREFIX}haylen_runtime${CMAKE_STATIC_LIBRARY_SUFFIX}")

haylen_static_closure(haylen_engine engine_archives engine_externals)
set(engine_inputs "")
set(built_archives)
foreach(archive IN LISTS engine_archives)
  string(APPEND engine_inputs "$<TARGET_FILE:${archive}>\n")
  get_target_property(imported "${archive}" IMPORTED)
  if(NOT imported)
    list(APPEND built_archives "${archive}")
  endif()
endforeach()
file(GENERATE OUTPUT "${sdk_libraries}/engine-inputs.txt" CONTENT "${engine_inputs}")
# The Android runtime carries the static library of GameActivity, which only the build tree of the engine names.
set(runtime_inputs "$<TARGET_FILE:haylen_platform>\n$<JOIN:$<TARGET_OBJECTS:haylen_runtime>,\n>\n")
if(ANDROID)
  string(APPEND runtime_inputs "$<TARGET_FILE:haylen_game_activity>\n")
endif()
file(GENERATE OUTPUT "${sdk_libraries}/runtime-inputs.txt" CONTENT "${runtime_inputs}")

if(APPLE)
  find_program(HAYLEN_LIBTOOL libtool HINTS /usr/bin REQUIRED)
  set(merge_kind libtool)
  set(merge_tool "${HAYLEN_LIBTOOL}")
elseif(MSVC)
  set(merge_kind lib)
  set(merge_tool "${CMAKE_AR}")
else()
  set(merge_kind mri)
  set(merge_tool "${CMAKE_AR}")
endif()

foreach(part engine runtime)
  add_custom_command(OUTPUT "${${part}_library}"
    COMMAND "${CMAKE_COMMAND}" -DKIND=${merge_kind} "-DTOOL=${merge_tool}" "-DOUTPUT=${${part}_library}" "-DINPUTS=${sdk_libraries}/${part}-inputs.txt" -P "${HAYLEN_CMAKE_DIR}/haylen-merge-archives.cmake"
    DEPENDS "${sdk_libraries}/${part}-inputs.txt" ${built_archives} haylen_platform haylen_runtime
    COMMENT "Merging the Haylen ${part} library."
    VERBATIM
  )
endforeach()
add_custom_target(haylen_sdk ALL DEPENDS "${engine_library}" "${runtime_library}")

# The package config receives what the engine target carries for its users, with the ImGui configuration pointing at its installed copy.
set(HAYLEN_SDK_DEPENDENCIES "")
if("Threads::Threads" IN_LIST engine_externals)
  set(HAYLEN_SDK_DEPENDENCIES "find_dependency(Threads)")
endif()
list(JOIN engine_externals ";" HAYLEN_SDK_EXTERNALS)
get_target_property(imgui_definitions haylen_imgui INTERFACE_COMPILE_DEFINITIONS)
list(FILTER imgui_definitions EXCLUDE REGEX "^IMGUI_USER_CONFIG=")
list(JOIN imgui_definitions ";" HAYLEN_SDK_DEFINITIONS)
get_target_property(HAYLEN_SDK_COMPILE_OPTIONS haylen_engine INTERFACE_COMPILE_OPTIONS)
get_target_property(HAYLEN_SDK_LINK_OPTIONS haylen_engine INTERFACE_LINK_OPTIONS)
foreach(options HAYLEN_SDK_COMPILE_OPTIONS HAYLEN_SDK_LINK_OPTIONS)
  if(NOT ${options})
    set(${options} "")
  endif()
endforeach()
set(HAYLEN_SDK_ENGINE_FILE "${CMAKE_STATIC_LIBRARY_PREFIX}haylen${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(HAYLEN_SDK_RUNTIME_FILE "${CMAKE_STATIC_LIBRARY_PREFIX}haylen_runtime${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(HAYLEN_SDK_CONFIG_DIR "${CMAKE_INSTALL_LIBDIR}/cmake/haylen")
set(HAYLEN_SDK_SHARE_DIR "${CMAKE_INSTALL_DATADIR}/haylen")
# The path from the config folder up to the prefix is computed from the names alone, since a root without a drive is no full path on Windows.
set(HAYLEN_SDK_PREFIX_FROM_CONFIG "/")
cmake_path(RELATIVE_PATH HAYLEN_SDK_PREFIX_FROM_CONFIG BASE_DIRECTORY "/${HAYLEN_SDK_CONFIG_DIR}")
configure_file("${HAYLEN_CMAKE_DIR}/haylen-config.cmake.in" "${sdk}/haylen-config.cmake" @ONLY)
write_basic_package_version_file("${sdk}/haylen-config-version.cmake" VERSION "${PROJECT_VERSION}" COMPATIBILITY SameMinorVersion)

get_target_property(lua_include varn_vendor_lua INTERFACE_INCLUDE_DIRECTORIES)
string(REGEX REPLACE "^\\$<BUILD_INTERFACE:(.*)>$" "\\1" lua_include "${lua_include}")

install(FILES "${engine_library}" "${runtime_library}" DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT haylen_sdk)
install(FILES "${sdk}/haylen-config.cmake" "${sdk}/haylen-config-version.cmake" DESTINATION "${HAYLEN_SDK_CONFIG_DIR}" COMPONENT haylen_sdk)
install(DIRECTORY "${HAYLEN_ENGINE_DIR}/include/" "${HAYLEN_GENERATED_INCLUDE_DIR}/" "${nlohmann_json_SOURCE_DIR}/include/" DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}" COMPONENT haylen_sdk)
install(FILES "${HAYLEN_ENGINE_DIR}/src/ui/ImGuiConfig.hpp" "${HAYLEN_ENGINE_DIR}/src/ui/ImGuiAssert.hpp" DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/haylen/ui" COMPONENT haylen_sdk)
install(FILES "${imgui_SOURCE_DIR}/imgui.h" "${imgui_SOURCE_DIR}/imconfig.h" "${imgui_SOURCE_DIR}/misc/cpp/imgui_stdlib.h" "${lua_include}/lua.h" "${lua_include}/luaconf.h" "${lua_include}/lualib.h" "${lua_include}/lauxlib.h" "${varn_SOURCE_DIR}/include/lua.hpp"
  DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}" COMPONENT haylen_sdk)
install(FILES "${HAYLEN_CMAKE_DIR}/haylen-app.cmake" "${HAYLEN_CMAKE_DIR}/haylen-link-content.cmake" DESTINATION "${HAYLEN_SDK_SHARE_DIR}/cmake" COMPONENT haylen_sdk)
install(DIRECTORY "${HAYLEN_ENGINE_DIR}/platform/web" "${HAYLEN_ENGINE_DIR}/platform/apple" DESTINATION "${HAYLEN_SDK_SHARE_DIR}/platform" COMPONENT haylen_sdk)
install(FILES "${HAYLEN_ENGINE_DIR}/src/platform/sokol/LuaPlayer.cpp" DESTINATION "${HAYLEN_SDK_SHARE_DIR}/src/platform/sokol" COMPONENT haylen_sdk)
if(APPLE)
  install(FILES "${HAYLEN_ENGINE_DIR}/src/platform/apple/AppleMain.cpp" DESTINATION "${HAYLEN_SDK_SHARE_DIR}/src/platform/apple" COMPONENT haylen_sdk)
endif()
